package id.bpdlh.fdb.core.common.utils

object Constants {
    const val DATE_FORMAT = "dd MMMM yyyy"
    const val DATE_FORMAT_API = "yyyy-MM-dd"
    const val NEW_DATE_FORMAT = "dd/MM/yyyy"
    const val DATE_FORMAT_DD_MM_YYYY = "dd MMM yyyy"
    const val ISO_DATE_FORMAT = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
    const val BEARER_TOKEN = "BEARER_TOKEN"
    const val LOGGED_IN = "LOGGED_IN"
    const val WAREHOUSE_ID = "WAREHOUSE_ID"
    const val USER_ID = "USER_ID"
    const val EMAIL_ID = "EMAIL_ID"
    const val ROLE = "ROLE"
    const val USER_TYPE = "USER_TYPE"
    const val FEATURE = "FEATURE"
    const val DATE_PICKER_TAG = "DatePicker"
    const val REQUEST_CODE_KTP = 1
    const val REQUEST_CODE_KK = 2
    const val REQUEST_CODE_DOKUMEN_PENDUKUNG = 3
    const val REQUEST_CODE_SWAFOTO = 4
    const val REQUEST_CODE_FOTO_RUMAH = 5
    const val REQUEST_CODE_FOTO_USAHA = 6
    const val REQUEST_CODE_DOKUMEN_LAINNYA = 7
    const val REQUEST_CODE_DOKUMEN_SK_BERITA_ACARA = 8
    const val REQUEST_CODE_DOKUMEN_AD_ART = 9
    const val REQUEST_CODE_DOKUMEN_SURAT_PENDAMPING = 10
    const val REQUEST_CODE_BUKTI_JAMINAN = 11
    const val REQUEST_CODE_ADD_FILE = 12
    const val REQUEST_CODE_CHANGE_FILE = 13
    const val REQUEST_CODE_IJIN_LAHAN = 14
    const val REQUEST_CODE_SURAT_TANAH = 15
    const val REQUEST_CODE_SURAT_JUAL_BELI = 16
    const val REQUEST_CODE_SPPT = 17
    const val REQUEST_CODE_FOTO_LAHAN = 18
    const val REQUEST_CODE_LAPORAN_LABA_RUGI = 19
    const val REQUEST_CODE_KTP_PASANGAN = 20
    const val REQUEST_CODE_JAMINAN = 21
    const val REQUEST_CODE_DATA_JAMINAN = 21
    const val ALAMAT_CODE_KTP = 1
    const val ALAMAT_CODE_DOMISILI = 2
    const val SUCCESS = 1
    const val WARNING = 2
    const val RESULT_CODE_LOCATION_CHOSEN = 1
    const val EXTRA_LATITUDE = "extra_latitude"
    const val EXTRA_LONGITUDE = "extra_longitude"
    const val BYTE_SIZE = 1024
    const val MAX_SIZE = 10 * 1024 * 1024
    const val TYPE_PERORANGAN = "Anggota"
    const val TYPE_KELOMPOK = "Kelompok"
    const val EXTRA_PEMBIAYAAN_PERHUTANAN = "extra_pembiayaan_perhutanan"
    const val EXTRA_DATA_DEBITUR = "extra_data_debitur"
    const val EXTRA_CATEGORY = "extra_category"
    const val PERHUTANAN_SOSIAL = "Perhutanan Sosial"
    const val NON_PERHUTANAN_SOSIAL = "Non Perhutanan Sosial"
    const val TUNDA_TEBANG = "Tunda Tebang"
    const val HASIL_HUTAN_BUKAN_KAYU = "Hasil Hutan Bukan Kayu"
    const val KOMODITAS_NON_KEHUTANAN = "Komoditas Non Kehutanan"
    const val NON_KEHUTANAN = "Non-Kehutanan"
    const val STATUS_DRAFT = "Draft"
    const val STATUS_ON_PROGRESS = "On Progress"
    const val STATUS_MENUNGGU_VERIFIKASI = "Menunggu Verifikasi"
    const val STATUS_DITOLAK = "Ditolak"
    const val STATUS_DISETUJUI = "Disetujui"
    const val NON_PERHUTANAN_SOSIAL_TYPE = "Non Perhutanan Sosial"
    const val PERHUTANAN_SOSIAL_TYPE = "Perhutanan Sosial"
    const val DIKELOLA_SENDIRI = 1
    const val DIKELOLA_ORANG_LAIN = 2
    const val MODAL_KERJA = 1
    const val INVESTASI = 2
    const val DATA_JAMINAN = 1
    const val DOKUMEN_PENGUASAAN_LAHAN = 2
    const val UBAH_LAYANAN = "ubah_layanan"
    const val LANJUTKAN_LAYANAN = "lanjutkan_layanan"
    const val REVOLVING = "Revolving"
    const val NON_REVOLVING = "Non Revolving"
    const val LAKI_LAKI = "Laki-laki"
    const val PEREMPUAN = "Perempuan"
    const val KEGIATAN_KELOMPOK = "Kegiatan Kelompok"
    const val MITRA_USAHA = "Mitra Usaha"
    const val GAMBARAN_UMUM = "Gambaran Umum"
}